# Generated by Django 4.2.4 on 2023-09-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffonly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('content', models.TextField(max_length=100, verbose_name='Отзыв')),
                ('publish', models.BooleanField(default=False, verbose_name='Состояние')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(default=5, verbose_name='Оценка')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staffonly.master', verbose_name='Мастер')),
            ],
        ),
    ]
